### ISSUE TITLE
[Bug] Install failed

### ISSUE THREAD

**Issue by alieeeeeeeen** [ritz078/starring#1]
Run the command:
 ```npm install --global starring```

Result: 
`
 ENOENT: no such file or directory, chmod '/Users/Users/.nvm/versions/node/v6.3.1/lib/node_modules/starring/dist/cli.js'
`

**Comment by ritz078** [comment]
Fixed in v0.1.1

**Comment by ritz078** [comment]
@eeeeeLin Let me know if it works now.

**Comment by alieeeeeeeen** [comment]
@ritz078 Sorry for the late response 😜
It works correctly right now  👍
