### ISSUE TITLE
Add argument prevent interactive prompt

### ISSUE THREAD

**Issue by ajsb85** [ritz078/starring#7]
Hi @ritz078 

Can you add an arg like this -y to prevent interactive prompt?

Regards.

**Comment by ritz078** [comment]
Why would you like to do that ?

**Comment by ajsb85** [comment]
It's an idea to don't lost time. 😸

**Comment by ritz078** [comment]
but if you don't need the prompt, you are going to select all that you can do with `starring --all`. That won't show you the prompt.

**Comment by ajsb85** [comment]
For `--all` you got the question:

_Are you sure you want to star all the 21 repos ?_

![image](https://cloud.githubusercontent.com/assets/663460/25040556/67507ed8-210a-11e7-9c3a-2610d16117ae.png)

**Comment by ritz078** [comment]
removed in 0.2.0
