### ISSUE TITLE
Brower Extension

### ISSUE THREAD

**Issue by ajsb85** [ritz078/starring#8]
I want to help you to build a Web Extension for the Browsers (Firefox, Chrome, Edge...).

Can you post here the idea?

http://producthunt.com

Regards.

**Comment by ritz078** [comment]
How will that work ?

**Comment by ajsb85** [comment]
Detect the `package.json` in the current branch and add a new button (starring) here:

![image](https://cloud.githubusercontent.com/assets/663460/25040588/aab618a4-210a-11e7-8451-75d970bcdefd.png)

**Comment by ritz078** [comment]
I don't think that will very useful. You don't want to star the dependencies of other projects. And if you are trying to star the dependencies of your project, its much easier from the CLI ?
